import React, { useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';

const TeamListItem = ({ team, isActive, onSelect }) => {
  return (
    <div 
      onClick={onSelect}
      className={`flex flex-col gap-1 p-4 text-left transition-colors group cursor-pointer ${
        isActive 
          ? 'bg-primary/5 border-r-4 border-primary' 
          : 'hover:bg-slate-50 dark:hover:bg-slate-800/50 border-r-4 border-transparent'
      }`}
    >
      <div className="flex justify-between items-start">
        <span className={`text-sm font-bold ${isActive ? 'text-primary' : 'text-slate-800 dark:text-slate-200 group-hover:text-primary'}`}>
          {team.name}
        </span>
        <span className={`text-[10px] font-medium uppercase ${isActive ? 'text-primary/60' : 'text-slate-400'}`}>
          {team.department}
        </span>
      </div>
      <span className={`text-xs line-clamp-1 ${isActive ? 'text-slate-600 dark:text-slate-400' : 'text-slate-500'}`}>
        {team.project}
      </span>
    </div>
  );
};

const NoteCard = ({ note }) => {
  return (
    <div className={`relative flex flex-col gap-3 bg-white dark:bg-slate-900 p-5 rounded-xl border border-slate-200 dark:border-slate-800 shadow-sm ${note.isAutoGenerated ? 'opacity-60' : ''}`}>
      <div className={`absolute -right-[24px] top-5 size-4 border-4 border-white dark:border-slate-800 rounded-full ${!note.isRead && !note.isAutoGenerated ? 'bg-primary' : 'bg-slate-300 dark:bg-slate-700'}`}></div>
      
      <div className="flex justify-between items-start">
        <div className="flex flex-col">
          <span className="text-xs font-bold text-slate-900 dark:text-white">{note.title}</span>
          <span className="text-[10px] text-slate-500 font-medium">{note.date} • {note.time}</span>
        </div>
        
        {note.isRead ? (
          <div className="flex items-center gap-1.5 px-2 py-1 rounded bg-green-50 dark:bg-green-900/20 text-green-600 dark:text-green-400">
            <span className="material-symbols-outlined text-xs">visibility</span>
            <span className="text-[10px] font-bold uppercase tracking-tight">تمت القراءة</span>
          </div>
        ) : (
          <div className="flex items-center gap-1.5 px-2 py-1 rounded bg-slate-50 dark:bg-slate-800 text-slate-500">
            <span className="material-symbols-outlined text-xs">visibility_off</span>
            <span className="text-[10px] font-bold uppercase tracking-tight">غير مقروء</span>
          </div>
        )}
      </div>

      <div className={`text-sm text-slate-600 dark:text-slate-400 leading-relaxed ${note.isAutoGenerated ? 'italic' : ''}`}>
        {note.content}
      </div>

      {note.hashtags && note.hashtags.length > 0 && (
        <div className="pt-3 border-t border-slate-100 dark:border-slate-800 flex gap-2">
          {note.hashtags.map((tag, idx) => (
            <span key={idx} className="px-2 py-1 rounded bg-slate-100 dark:bg-slate-800 text-slate-500 text-[10px] font-medium">
              {tag}
            </span>
          ))}
        </div>
      )}
    </div>
  );
};

const SupervisorNotes = () => {
  const [teams, setTeams] = useState([
    { 
      id: "alpha", 
      name: "فريق ألفا", 
      department: "علوم حاسوب",
      project: "مساعد الرعاية الصحية بالذكاء الاصطناعي",
      isActive: true 
    },
    { 
      id: "beta", 
      name: "فريق بيتا", 
      department: "هندسة كهربائية",
      project: "محسن الشبكة الذكية",
      isActive: false 
    },
    { 
      id: "gamma", 
      name: "فريق جاما", 
      department: "علوم حاسوب",
      project: "نظام تصويت بالبلوكشين",
      isActive: false 
    },
    { 
      id: "delta", 
      name: "فريق دلتا", 
      department: "تقنية معلومات",
      project: "أداة تعليم الواقع المعزز",
      isActive: false 
    }
  ]);

  const [notes, setNotes] = useState([
    {
      id: 1,
      teamId: "alpha",
      title: "ملاحظة اجتماع: مراجعة الأدبيات",
      date: "٢٤ أكتوبر ٢٠٢٣",
      time: "٠٢:٣٠ م",
      content: "حدد الفريق بنجاح مجموعات البيانات الأساسية لنموذج التعلم الآلي. ومع ذلك، تحتاج مراجعة الأدبيات إلى مزيد من التركيز على الذكاء الاصطناعي القابل للتفسير في الرعاية الصحية. يرجى الرجوع إلى الأوراق التي شاركتها على محرك الأقراص المشترك. الأسبوع المقبل سنناقش البنية الأولية.",
      isRead: true,
      hashtags: ["#مراجعة_الأدبيات", "#تجهيز_البيانات"],
      isAutoGenerated: false
    },
    {
      id: 2,
      teamId: "alpha",
      title: "الانطلاق وأهداف المشروع",
      date: "١٠ أكتوبر ٢٠٢٣",
      time: "١٠:٠٠ ص",
      content: "تمت الموافقة على نطاق المشروع الأولي. التركيز على الذكاء الاصطناعي للتشخيص جيد. تأكد من وضع جدول زمني واضح لتطوير الحد الأدنى من المنتج القابل للتطبيق بحلول نهاية هذا الشهر. يجب على قادة الفرق تحديد الأدوار الفردية داخل المشروع.",
      isRead: false,
      hashtags: [],
      isAutoGenerated: false
    },
    {
      id: 3,
      teamId: "alpha",
      title: "تعيين المشرف",
      date: "٢٨ سبتمبر ٢٠٢٣",
      time: "١١:١٥ ص",
      content: "تم تعيين د. سارة جميل كمشرف لفريق ألفا.",
      isRead: true,
      hashtags: [],
      isAutoGenerated: true
    }
  ]);

  const [searchParams, setSearchParams] = useSearchParams();
  const initialTeamId = searchParams.get('team') || "alpha";

  const [selectedTeamId, setSelectedTeamId] = useState(initialTeamId);
  const [newNoteContent, setNewNoteContent] = useState("");
  const [newNoteTitle, setNewNoteTitle] = useState("");
  const [isSubmitting, setIsSubmitting] = useState(false);

  const handleTeamSelect = (id) => {
    setSelectedTeamId(id);
    setSearchParams({ team: id });
  };

  const handleNewNoteChange = (val) => setNewNoteContent(val);
  const handleNewNoteTitleChange = (val) => setNewNoteTitle(val);

  const handleAddNote = () => {
    if (!newNoteContent.trim() || !newNoteTitle.trim()) {
      alert("يرجى تعبئة عنوان ومحتوى الملاحظة");
      return;
    }
    
    setIsSubmitting(true);
    setTimeout(() => {
      const newNote = {
        id: Date.now(),
        teamId: selectedTeamId,
        title: newNoteTitle,
        date: "الآن",
        time: "الآن",
        content: newNoteContent,
        isRead: false,
        hashtags: [],
        isAutoGenerated: false
      };
      
      setNotes([newNote, ...notes]);
      setNewNoteTitle("");
      setNewNoteContent("");
      setIsSubmitting(false);
      console.log("Added Note:", newNote);
    }, 600);
  };

  const handleDownloadReport = () => {
    console.log("Downloading report for team:", selectedTeamId);
  };

  const handleFormatText = (format) => {
    console.log("Formatting text:", format);
  };

  const selectedTeam = teams.find(t => t.id === selectedTeamId);
  const filteredNotes = notes.filter(n => n.teamId === selectedTeamId);

  return (
    <div className="flex flex-col gap-6 w-full max-w-7xl mx-auto min-h-screen">
      {/* Breadcrumbs */}
      <nav className="flex items-center gap-2 text-sm text-slate-500 dark:text-slate-400 mb-6 shrink-0">
        <Link to="/supervisor/dashboard" className="hover:text-primary">الرئيسية</Link>
        <span className="material-symbols-outlined text-sm">chevron_right</span>
        <span className="text-slate-900 dark:text-white font-medium">الملاحظات</span>
      </nav>

      <div className="flex flex-col lg:flex-row flex-1 gap-6 pb-10">
        {/* Left Column - Teams List */}
        <aside className="w-full lg:w-80 flex flex-col gap-4 shrink-0">
          <div className="bg-white dark:bg-slate-900 rounded-xl border border-slate-200 dark:border-slate-800 overflow-hidden shadow-sm">
            <div className="p-4 border-b border-slate-200 dark:border-slate-800 flex justify-between items-center">
              <h3 className="font-bold text-slate-900 dark:text-white">قائمة الفرق</h3>
              <span className="bg-primary/10 text-primary text-[10px] px-2 py-0.5 rounded font-bold uppercase tracking-wider">نشطة</span>
            </div>
            <div className="flex flex-col max-h-[calc(100vh-200px)] overflow-y-auto divide-y divide-slate-100 dark:divide-slate-800">
              {teams.map(team => (
                <TeamListItem 
                  key={team.id}
                  team={team}
                  isActive={selectedTeamId === team.id}
                  onSelect={() => handleTeamSelect(team.id)}
                />
              ))}
            </div>
          </div>
        </aside>

        {/* Right Column - Notes Area */}
        <section className="flex-1 flex flex-col gap-6">
          {/* Header */}
          <div className="flex flex-col gap-1">
            <div className="flex items-center gap-2">
              <h1 className="text-2xl font-black text-slate-900 dark:text-white tracking-tight">سجل ملاحظات المشرف</h1>
              <span className="px-2 py-0.5 rounded bg-primary text-white text-[10px] font-bold">
                {selectedTeam?.name}
              </span>
            </div>
            <p className="text-slate-500 text-sm">
              مراجعة الملاحظات لـ <span className="font-semibold text-slate-700 dark:text-slate-300">{selectedTeam?.project}</span>
            </p>
          </div>

          {/* Add New Note Section */}
          <div className="bg-white dark:bg-slate-900 rounded-xl border border-slate-200 dark:border-slate-800 p-5 shadow-sm">
            <div className="flex items-center gap-2 mb-4">
              <span className="material-symbols-outlined text-primary text-lg">edit_note</span>
              <h3 className="font-bold text-slate-900 dark:text-white">إضافة ملاحظة جديدة</h3>
            </div>
            <div className="flex flex-col gap-4">
              <input 
                type="text"
                value={newNoteTitle}
                onChange={(e) => handleNewNoteTitleChange(e.target.value)}
                placeholder="عنوان الملاحظة"
                className="w-full p-3 border border-slate-200 dark:border-slate-700 rounded-lg bg-slate-50 dark:bg-slate-800 text-sm focus:ring-2 focus:ring-primary/20 focus:border-primary text-slate-900 dark:text-white"
              />
              <div className="border border-slate-200 dark:border-slate-800 rounded-lg overflow-hidden">
                <div className="bg-slate-50 dark:bg-slate-800/50 border-b border-slate-200 dark:border-slate-800 p-2 flex gap-2">
                  <button onClick={() => handleFormatText('bold')} className="p-1 hover:bg-white dark:hover:bg-slate-700 rounded transition-colors">
                    <span className="material-symbols-outlined text-sm">format_bold</span>
                  </button>
                  <button onClick={() => handleFormatText('italic')} className="p-1 hover:bg-white dark:hover:bg-slate-700 rounded transition-colors">
                    <span className="material-symbols-outlined text-sm">format_italic</span>
                  </button>
                  <button onClick={() => handleFormatText('list')} className="p-1 hover:bg-white dark:hover:bg-slate-700 rounded transition-colors">
                    <span className="material-symbols-outlined text-sm">format_list_bulleted</span>
                  </button>
                  <button onClick={() => handleFormatText('link')} className="p-1 hover:bg-white dark:hover:bg-slate-700 rounded transition-colors">
                    <span className="material-symbols-outlined text-sm">link</span>
                  </button>
                </div>
                <textarea 
                  value={newNoteContent}
                  onChange={(e) => handleNewNoteChange(e.target.value)}
                  className="w-full min-h-[100px] p-4 border-none focus:ring-0 bg-transparent text-sm placeholder:text-slate-400 text-slate-900 dark:text-white"
                  placeholder="اكتب ملاحظاتك أو ملاحظاتك أو خطواتك التالية هنا..."
                />
              </div>
              <div className="flex flex-wrap justify-between items-center gap-4">
                <span className="text-[10px] text-slate-400 font-medium">سيتم إشعار الطلاب فور النشر.</span>
                <button 
                  onClick={handleAddNote}
                  disabled={isSubmitting || !newNoteContent.trim() || !newNoteTitle.trim()}
                  className="bg-primary hover:bg-primary/90 text-white px-5 py-2 rounded-lg font-bold text-sm flex items-center gap-2 transition-all disabled:opacity-50"
                >
                  <span className="material-symbols-outlined text-sm">send</span>
                  {isSubmitting ? 'جاري الإضافة...' : 'إضافة ملاحظة'}
                </button>
              </div>
            </div>
          </div>

          {/* Notes History Section */}
          <div className="flex flex-col gap-4">
            <div className="flex items-center justify-between">
              <h3 className="font-bold text-slate-900 dark:text-white flex items-center gap-2">
                <span className="material-symbols-outlined text-slate-400">history</span>
                سجل الملاحظات
              </h3>
              <button onClick={handleDownloadReport} className="text-xs font-semibold text-primary hover:underline">
                تحميل التقرير
              </button>
            </div>

            {/* Timeline */}
            <div className="relative flex flex-col gap-4 pr-4 before:content-[''] before:absolute before:right-[11px] before:top-2 before:bottom-2 before:w-[2px] before:bg-slate-200 dark:before:bg-slate-800">
              {filteredNotes.length > 0 ? (
                filteredNotes.map(note => (
                  <NoteCard key={note.id} note={note} />
                ))
              ) : (
                <div className="text-center p-8 bg-slate-50 dark:bg-slate-800/30 rounded-xl text-slate-500">
                  لا توجد ملاحظات لهذا الفريق حتى الآن.
                </div>
              )}
            </div>
          </div>
        </section>
      </div>
    </div>
  );
};

export default SupervisorNotes;
